### ISSUE TITLE
Homebrew for macOS and Linux? Winget for Windoze?

### ISSUE THREAD

**Issue by ylluminate** [labi-le/belphegor#21]
It would be really amazing if we could get a Homebrew recipe similar to uniclip that will work for macOS and Linux systems. Claude and ChatGPT can make Homebrew recipes pretty well.

Additionally, it would be great to see an easy way to start it up with the system and with a config file in the appropriate Homebrew etc folder. Having it easily updateable on many machines would be fantastic. Claude and ChatGPT can make quick work of startup files as can Lingon X on macOS so it's not the end of the world if you can't figure this out, but it would be cool to have it easily enableable similar to other Homebrew recipes that facilitate an option to insert startups.

If Windows could have a method to do this as well that would be another incredible bonus, but I'm not sure of the "best" way to do that on Winbloze except through `winget` in terms of universality.

**Comment by labi-le** [comment]
if you're willing to help implement a public package, you're welcome. i use the release page

https://github.com/labi-le/belphegor/releases
