### ISSUE TITLE
Resolve hostnames?

### ISSUE THREAD

**Issue by ylluminate** [labi-le/belphegor#25]
I've got a scenario where I use a laptop as my primary system and it's IP address changes based on whether I'm using the ethernet or the wi-fi as my primary network interface.

I'd prefer to use the hostname I have that resolves (or even better, Bonjour/Rendezvous/mDNS) so that the connection will be more durable and easily configurable.

Ultimately this also brings up another point that I'll make in another ticket re: watching for failures and restarting clients connected to the server if/when any changes or timeouts occur.

**Comment by labi-le** [comment]
good idea

**Comment by labi-le** [comment]
![image](https://github.com/user-attachments/assets/ace3a2b0-ff83-4da3-865e-df0134ffcc35)
еhis possibility has existed before
